[2020-04-20 02:21:47 +0000] [18976] [INFO] Starting gunicorn 20.0.4
[2020-04-20 02:21:47 +0000] [18976] [INFO] Listening at: http://0.0.0.0:8880 (18976)
[2020-04-20 02:21:47 +0000] [18976] [INFO] Using worker: sync
[2020-04-20 02:21:47 +0000] [18979] [INFO] Booting worker with pid: 18979
[2020-04-20 02:21:47 +0000] [18980] [INFO] Booting worker with pid: 18980
 ›   Warning: heroku update available from 7.39.0 to 7.39.3.
 ›   Warning: heroku update available from 7.39.0 to 7.39.3.
[2020-04-20 02:29:18 +0000] [18976] [INFO] Handling signal: term
[2020-04-20 02:29:18 +0000] [18979] [INFO] Worker exiting (pid: 18979)
[2020-04-20 02:29:18 +0000] [18980] [INFO] Worker exiting (pid: 18980)
[2020-04-20 02:29:18 +0000] [18976] [INFO] Shutting down: Master
[2020-04-20 02:29:24 +0000] [19340] [INFO] Starting gunicorn 20.0.4
[2020-04-20 02:29:24 +0000] [19340] [INFO] Listening at: http://0.0.0.0:8880 (19340)
[2020-04-20 02:29:24 +0000] [19340] [INFO] Using worker: sync
[2020-04-20 02:29:24 +0000] [19343] [INFO] Booting worker with pid: 19343
[2020-04-20 02:29:24 +0000] [19344] [INFO] Booting worker with pid: 19344
 ›   Warning: heroku update available from 7.39.0 to 7.39.3.
 ›   Warning: heroku update available from 7.39.0 to 7.39.3.
[2020-04-20 02:29:28,525] ERROR in app: Exception on /temp/wiki [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/pi.sminfo.me/app.py", line 21, in wiki
    return render_template("wiki.html", data0=data0)
  File "/usr/local/lib/python3.6/dist-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.6/dist-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/var/www/pi.sminfo.me/templates/wiki.html", line 17, in template
    <a class="nav-link" href="https://pi.sminfo.me">Current Raspberry Pi Temp: {{int{data0}}</a>
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got '{'
[2020-04-20 02:29:37,229] ERROR in app: Exception on /temp/wiki [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/pi.sminfo.me/app.py", line 21, in wiki
    return render_template("wiki.html", data0=data0)
  File "/usr/local/lib/python3.6/dist-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.6/dist-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/var/www/pi.sminfo.me/templates/wiki.html", line 17, in template
    <a class="nav-link" href="https://pi.sminfo.me">Current Raspberry Pi Temp: {{int{data0}}</a>
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got '{'
[2020-04-20 02:29:39,001] ERROR in app: Exception on /temp/wiki [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/pi.sminfo.me/app.py", line 21, in wiki
    return render_template("wiki.html", data0=data0)
  File "/usr/local/lib/python3.6/dist-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.6/dist-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/var/www/pi.sminfo.me/templates/wiki.html", line 17, in template
    <a class="nav-link" href="https://pi.sminfo.me">Current Raspberry Pi Temp: {{int{data0}}</a>
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got '{'
[2020-04-20 02:29:40,202] ERROR in app: Exception on /temp/wiki [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/pi.sminfo.me/app.py", line 21, in wiki
    return render_template("wiki.html", data0=data0)
  File "/usr/local/lib/python3.6/dist-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.6/dist-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/var/www/pi.sminfo.me/templates/wiki.html", line 17, in template
    <a class="nav-link" href="https://pi.sminfo.me">Current Raspberry Pi Temp: {{int{data0}}</a>
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got '{'
[2020-04-20 02:29:44,182] ERROR in app: Exception on /temp/wiki [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/pi.sminfo.me/app.py", line 21, in wiki
    return render_template("wiki.html", data0=data0)
  File "/usr/local/lib/python3.6/dist-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.6/dist-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/var/www/pi.sminfo.me/templates/wiki.html", line 17, in template
    <a class="nav-link" href="https://pi.sminfo.me">Current Raspberry Pi Temp: {{int{data0}}</a>
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got '{'
[2020-04-20 02:30:00 +0000] [19340] [INFO] Handling signal: term
[2020-04-20 02:30:00 +0000] [19343] [INFO] Worker exiting (pid: 19343)
[2020-04-20 02:30:00 +0000] [19344] [INFO] Worker exiting (pid: 19344)
[2020-04-20 02:30:00 +0000] [19340] [INFO] Shutting down: Master
[2020-04-20 02:37:08 +0000] [19831] [INFO] Starting gunicorn 20.0.4
[2020-04-20 02:37:08 +0000] [19831] [INFO] Listening at: http://0.0.0.0:8880 (19831)
[2020-04-20 02:37:08 +0000] [19831] [INFO] Using worker: sync
[2020-04-20 02:37:08 +0000] [19834] [INFO] Booting worker with pid: 19834
[2020-04-20 02:37:08 +0000] [19835] [INFO] Booting worker with pid: 19835
 ›   Warning: heroku update available from 7.39.0 to 7.39.3.
 ›   Warning: heroku update available from 7.39.0 to 7.39.3.
[2020-04-20 02:38:13 +0000] [19831] [INFO] Handling signal: term
[2020-04-20 02:38:13 +0000] [19834] [INFO] Worker exiting (pid: 19834)
[2020-04-20 02:38:13 +0000] [19835] [INFO] Worker exiting (pid: 19835)
[2020-04-20 02:38:13 +0000] [19831] [INFO] Shutting down: Master
[2020-04-20 02:38:22 +0000] [19976] [INFO] Starting gunicorn 20.0.4
[2020-04-20 02:38:22 +0000] [19976] [INFO] Listening at: http://0.0.0.0:8880 (19976)
[2020-04-20 02:38:22 +0000] [19976] [INFO] Using worker: sync
[2020-04-20 02:38:22 +0000] [19997] [INFO] Booting worker with pid: 19997
[2020-04-20 02:38:22 +0000] [19998] [INFO] Booting worker with pid: 19998
 ›   Warning: heroku update available from 7.39.0 to 7.39.3.
 ›   Warning: heroku update available from 7.39.0 to 7.39.3.
