[2020-04-17 02:25:06 +0000] [9668] [INFO] Starting gunicorn 20.0.4
[2020-04-17 02:25:06 +0000] [9668] [ERROR] Connection in use: ('0.0.0.0', 8880)
[2020-04-17 02:25:06 +0000] [9668] [ERROR] Retrying in 1 second.
[2020-04-17 02:25:07 +0000] [9668] [ERROR] Connection in use: ('0.0.0.0', 8880)
[2020-04-17 02:25:07 +0000] [9668] [ERROR] Retrying in 1 second.
[2020-04-17 02:25:08 +0000] [9668] [ERROR] Connection in use: ('0.0.0.0', 8880)
[2020-04-17 02:25:08 +0000] [9668] [ERROR] Retrying in 1 second.
[2020-04-17 02:25:09 +0000] [9668] [ERROR] Connection in use: ('0.0.0.0', 8880)
[2020-04-17 02:25:09 +0000] [9668] [ERROR] Retrying in 1 second.
[2020-04-17 02:25:10 +0000] [9668] [ERROR] Connection in use: ('0.0.0.0', 8880)
[2020-04-17 02:25:10 +0000] [9668] [ERROR] Retrying in 1 second.
[2020-04-17 02:25:11 +0000] [9668] [ERROR] Can't connect to ('0.0.0.0', 8880)
[2020-04-17 02:46:13 +0000] [10126] [INFO] Starting gunicorn 20.0.4
[2020-04-17 02:46:13 +0000] [10126] [INFO] Listening at: http://0.0.0.0:8880 (10126)
[2020-04-17 02:46:13 +0000] [10126] [INFO] Using worker: sync
[2020-04-17 02:46:13 +0000] [10129] [INFO] Booting worker with pid: 10129
[2020-04-17 02:52:34 +0000] [10126] [INFO] Handling signal: term
[2020-04-17 02:52:34 +0000] [10129] [INFO] Worker exiting (pid: 10129)
[2020-04-17 02:52:34 +0000] [10126] [INFO] Shutting down: Master
[2020-04-17 02:52:40 +0000] [10140] [INFO] Starting gunicorn 20.0.4
[2020-04-17 02:52:40 +0000] [10140] [INFO] Listening at: http://0.0.0.0:8880 (10140)
[2020-04-17 02:52:40 +0000] [10140] [INFO] Using worker: sync
[2020-04-17 02:52:40 +0000] [10143] [INFO] Booting worker with pid: 10143
[2020-04-17 03:12:28 +0000] [10140] [INFO] Handling signal: term
[2020-04-17 03:12:28 +0000] [10143] [INFO] Worker exiting (pid: 10143)
[2020-04-17 03:12:28 +0000] [10140] [INFO] Shutting down: Master
[2020-04-17 03:15:06 +0000] [10821] [INFO] Starting gunicorn 20.0.4
[2020-04-17 03:15:06 +0000] [10821] [INFO] Listening at: http://0.0.0.0:8880 (10821)
[2020-04-17 03:15:06 +0000] [10821] [INFO] Using worker: sync
[2020-04-17 03:15:06 +0000] [10824] [INFO] Booting worker with pid: 10824
[2020-04-17 11:59:24,830] ERROR in app: Exception on /temp [GET]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/mysql/connector/connection_cext.py", line 489, in cmd_query
    raw_as_string=raw_as_string)
_mysql_connector.MySQLInterfaceError: Lost connection to MySQL server during query

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/pi.sminfo.me/app.py", line 8, in display_tables
    cursor.execute("SELECT * FROM pitemp order by temp_id desc;")
  File "/home/ubuntu/.local/lib/python3.6/site-packages/mysql/connector/cursor_cext.py", line 266, in execute
    raw_as_string=self._raw_as_string)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/mysql/connector/connection_cext.py", line 492, in cmd_query
    sqlstate=exc.sqlstate)
mysql.connector.errors.OperationalError: 2013 (HY000): Lost connection to MySQL server during query
[2020-04-17 11:59:25,393] ERROR in app: Exception on /temp [GET]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/mysql/connector/connection_cext.py", line 489, in cmd_query
    raw_as_string=raw_as_string)
_mysql_connector.MySQLInterfaceError: MySQL server has gone away

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/pi.sminfo.me/app.py", line 8, in display_tables
    cursor.execute("SELECT * FROM pitemp order by temp_id desc;")
  File "/home/ubuntu/.local/lib/python3.6/site-packages/mysql/connector/cursor_cext.py", line 266, in execute
    raw_as_string=self._raw_as_string)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/mysql/connector/connection_cext.py", line 492, in cmd_query
    sqlstate=exc.sqlstate)
mysql.connector.errors.DatabaseError: 2006 (HY000): MySQL server has gone away
[2020-04-17 12:00:44 +0000] [10821] [INFO] Handling signal: term
[2020-04-17 12:00:44 +0000] [10824] [INFO] Worker exiting (pid: 10824)
[2020-04-17 12:00:44 +0000] [10821] [INFO] Shutting down: Master
[2020-04-17 13:17:16 +0000] [17565] [INFO] Starting gunicorn 20.0.4
[2020-04-17 13:17:16 +0000] [17565] [INFO] Listening at: http://0.0.0.0:8880 (17565)
[2020-04-17 13:17:16 +0000] [17565] [INFO] Using worker: sync
[2020-04-17 13:17:16 +0000] [17568] [INFO] Booting worker with pid: 17568
[2020-04-17 14:24:06 +0000] [20137] [INFO] Starting gunicorn 20.0.4
[2020-04-17 14:24:06 +0000] [20137] [ERROR] Connection in use: ('0.0.0.0', 8880)
[2020-04-17 14:24:06 +0000] [20137] [ERROR] Retrying in 1 second.
[2020-04-17 14:24:07 +0000] [20137] [ERROR] Connection in use: ('0.0.0.0', 8880)
[2020-04-17 14:24:07 +0000] [20137] [ERROR] Retrying in 1 second.
[2020-04-17 14:24:08 +0000] [20137] [ERROR] Connection in use: ('0.0.0.0', 8880)
[2020-04-17 14:24:08 +0000] [20137] [ERROR] Retrying in 1 second.
[2020-04-17 14:24:09 +0000] [20137] [ERROR] Connection in use: ('0.0.0.0', 8880)
[2020-04-17 14:24:09 +0000] [20137] [ERROR] Retrying in 1 second.
[2020-04-17 14:24:10 +0000] [20137] [ERROR] Connection in use: ('0.0.0.0', 8880)
[2020-04-17 14:24:10 +0000] [20137] [ERROR] Retrying in 1 second.
[2020-04-17 14:24:11 +0000] [20137] [ERROR] Can't connect to ('0.0.0.0', 8880)
[2020-04-17 14:32:57 +0000] [20517] [INFO] Starting gunicorn 20.0.4
[2020-04-17 14:32:57 +0000] [20517] [ERROR] Connection in use: ('0.0.0.0', 8880)
[2020-04-17 14:32:57 +0000] [20517] [ERROR] Retrying in 1 second.
[2020-04-17 14:32:58 +0000] [20517] [ERROR] Connection in use: ('0.0.0.0', 8880)
[2020-04-17 14:32:58 +0000] [20517] [ERROR] Retrying in 1 second.
[2020-04-17 14:32:59 +0000] [20517] [ERROR] Connection in use: ('0.0.0.0', 8880)
[2020-04-17 14:32:59 +0000] [20517] [ERROR] Retrying in 1 second.
[2020-04-17 14:33:00 +0000] [20517] [ERROR] Connection in use: ('0.0.0.0', 8880)
[2020-04-17 14:33:00 +0000] [20517] [ERROR] Retrying in 1 second.
[2020-04-17 14:33:01 +0000] [20517] [ERROR] Connection in use: ('0.0.0.0', 8880)
[2020-04-17 14:33:01 +0000] [20517] [ERROR] Retrying in 1 second.
[2020-04-17 14:33:02 +0000] [20517] [ERROR] Can't connect to ('0.0.0.0', 8880)
[2020-04-17 15:28:21 +0000] [17568] [INFO] Worker exiting (pid: 17568)
[2020-04-17 15:28:21 +0000] [17565] [INFO] Handling signal: term
[2020-04-17 15:28:22 +0000] [17565] [INFO] Shutting down: Master
[2020-04-17 15:30:05 +0000] [25386] [INFO] Starting gunicorn 20.0.4
[2020-04-17 15:30:05 +0000] [25386] [INFO] Listening at: http://0.0.0.0:8880 (25386)
[2020-04-17 15:30:05 +0000] [25386] [INFO] Using worker: sync
[2020-04-17 15:30:05 +0000] [25389] [INFO] Booting worker with pid: 25389
[2020-04-17 16:01:43 +0000] [25386] [INFO] Handling signal: term
[2020-04-17 16:01:43 +0000] [25389] [INFO] Worker exiting (pid: 25389)
[2020-04-17 16:01:43 +0000] [25386] [INFO] Shutting down: Master
[2020-04-17 16:04:55 +0000] [26812] [INFO] Starting gunicorn 20.0.4
[2020-04-17 16:04:55 +0000] [26812] [INFO] Listening at: http://0.0.0.0:8880 (26812)
[2020-04-17 16:04:55 +0000] [26812] [INFO] Using worker: sync
[2020-04-17 16:04:55 +0000] [26815] [INFO] Booting worker with pid: 26815
[2020-04-17 16:09:41 +0000] [26812] [INFO] Handling signal: term
[2020-04-17 16:09:41 +0000] [26815] [INFO] Worker exiting (pid: 26815)
[2020-04-17 16:09:41 +0000] [26812] [INFO] Shutting down: Master
[2020-04-17 16:09:46 +0000] [27124] [INFO] Starting gunicorn 20.0.4
[2020-04-17 16:09:46 +0000] [27124] [INFO] Listening at: http://0.0.0.0:8880 (27124)
[2020-04-17 16:09:46 +0000] [27124] [INFO] Using worker: sync
[2020-04-17 16:09:46 +0000] [27127] [INFO] Booting worker with pid: 27127
[2020-04-17 16:11:10 +0000] [27124] [INFO] Handling signal: term
[2020-04-17 16:11:10 +0000] [27127] [INFO] Worker exiting (pid: 27127)
[2020-04-17 16:11:10 +0000] [27124] [INFO] Shutting down: Master
[2020-04-17 16:12:04 +0000] [27262] [INFO] Starting gunicorn 20.0.4
[2020-04-17 16:12:04 +0000] [27262] [INFO] Listening at: http://0.0.0.0:8880 (27262)
[2020-04-17 16:12:04 +0000] [27262] [INFO] Using worker: sync
[2020-04-17 16:12:05 +0000] [27265] [INFO] Booting worker with pid: 27265
[2020-04-17 16:12:40 +0000] [27262] [INFO] Handling signal: term
[2020-04-17 16:12:40 +0000] [27265] [INFO] Worker exiting (pid: 27265)
[2020-04-17 16:12:40 +0000] [27262] [INFO] Shutting down: Master
[2020-04-17 16:12:40 +0000] [27273] [INFO] Starting gunicorn 20.0.4
[2020-04-17 16:12:40 +0000] [27273] [INFO] Listening at: http://0.0.0.0:8880 (27273)
[2020-04-17 16:12:40 +0000] [27273] [INFO] Using worker: sync
[2020-04-17 16:12:40 +0000] [27276] [INFO] Booting worker with pid: 27276
[2020-04-17 16:12:40 +0000] [27276] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'wgsi'
[2020-04-17 16:12:40 +0000] [27276] [INFO] Worker exiting (pid: 27276)
[2020-04-17 16:12:41 +0000] [27273] [INFO] Shutting down: Master
[2020-04-17 16:12:41 +0000] [27273] [INFO] Reason: Worker failed to boot.
[2020-04-17 16:13:03 +0000] [27308] [INFO] Starting gunicorn 20.0.4
[2020-04-17 16:13:03 +0000] [27308] [INFO] Listening at: http://0.0.0.0:8880 (27308)
[2020-04-17 16:13:03 +0000] [27308] [INFO] Using worker: sync
[2020-04-17 16:13:03 +0000] [27311] [INFO] Booting worker with pid: 27311
[2020-04-17 16:21:18 +0000] [27308] [INFO] Handling signal: term
[2020-04-17 16:21:18 +0000] [27311] [INFO] Worker exiting (pid: 27311)
[2020-04-17 16:21:19 +0000] [27308] [INFO] Shutting down: Master
[2020-04-17 17:20:49 +0000] [30676] [INFO] Starting gunicorn 20.0.4
[2020-04-17 17:20:49 +0000] [30676] [INFO] Listening at: http://0.0.0.0:8880 (30676)
[2020-04-17 17:20:49 +0000] [30676] [INFO] Using worker: sync
[2020-04-17 17:20:49 +0000] [30679] [INFO] Booting worker with pid: 30679
