[2020-04-17 03:12:31 +0000] [10779] [INFO] Starting gunicorn 20.0.4
[2020-04-17 03:12:31 +0000] [10779] [INFO] Listening at: http://0.0.0.0:8880 (10779)
[2020-04-17 03:12:31 +0000] [10779] [INFO] Using worker: sync
[2020-04-17 03:12:31 +0000] [10782] [INFO] Booting worker with pid: 10782
[2020-04-17 03:12:31 +0000] [10782] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'wsgi'
[2020-04-17 03:12:31 +0000] [10782] [INFO] Worker exiting (pid: 10782)
[2020-04-17 03:12:31 +0000] [10779] [INFO] Shutting down: Master
[2020-04-17 03:12:31 +0000] [10779] [INFO] Reason: Worker failed to boot.
[2020-04-17 16:11:14 +0000] [27223] [INFO] Starting gunicorn 20.0.4
[2020-04-17 16:11:14 +0000] [27223] [INFO] Listening at: http://0.0.0.0:8880 (27223)
[2020-04-17 16:11:14 +0000] [27223] [INFO] Using worker: sync
[2020-04-17 16:11:14 +0000] [27226] [INFO] Booting worker with pid: 27226
[2020-04-17 16:11:14 +0000] [27226] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'wsgi'
[2020-04-17 16:11:14 +0000] [27226] [INFO] Worker exiting (pid: 27226)
[2020-04-17 16:11:14 +0000] [27223] [INFO] Shutting down: Master
[2020-04-17 16:11:14 +0000] [27223] [INFO] Reason: Worker failed to boot.
